// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogcyavomnkpsiheyojeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nY3lhdm9tbmtwc2loZXlvamVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDA2ODcsImV4cCI6MjA2MDYxNjY4N30.9cXJ1rjbmJVOnlIQWc4Tx3zOx-hkyCBWuuSK9tCw68Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);